"""
Regenerate `_index/done-index.md`, `_index/wip-index.md`, `_index/unmapped-index.md`
by scanning stub filenames `[D|W|U]-DONE-*.md` under
{bugs,discoveries,prd-asks}/{tech_layer}/.

Each index groups items by `module / sheet` (parsed from stub frontmatter) and lists
each row's status, raw status, link to stub.

Run any time stubs change (e.g. after manually flipping `[W]` → `[D]`).
"""
from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
INDEX_DIR = BASE / "_index"
TRIAGE_DATE = "2026-05-09"


def parse_stub(path: Path) -> dict | None:
    """Pull header fields out of a stub file."""
    text = path.read_text(encoding="utf-8")
    title_m = re.search(r"^# (\[[DWU]\]-DONE-\d+): (.+)$", text, re.M)
    if not title_m:
        return None
    fields = {"id": title_m.group(1), "title": title_m.group(2).strip(), "path": path}
    for key, label in [
        ("status", "Status"),
        ("type_guess", "Type guess"),
        ("tech_layer", "Tech layer guess"),
        ("module", "Module / Sheet"),
        ("source", "Source"),
        ("status_raw", "Raw status in Excel"),
    ]:
        m = re.search(rf"^- \*\*{re.escape(label)}\*\*:\s*(.+)$", text, re.M)
        if m:
            fields[key] = m.group(1).strip()
    # Clean: tech_layer "`frontend-config` (heuristic ...)" → "frontend-config"
    if "tech_layer" in fields:
        tm = re.match(r"`([^`]+)`", fields["tech_layer"])
        if tm:
            fields["tech_layer"] = tm.group(1)
    # Clean: module "`Sheet7` → slug `sheet7-misc`" → ("Sheet7", "sheet7-misc")
    if "module" in fields:
        mm = re.match(r"`([^`]+)`", fields["module"])
        if mm:
            fields["module_name"] = mm.group(1)
    # Clean: status_raw "`Đã fixed`" → "Đã fixed"
    if "status_raw" in fields:
        fields["status_raw"] = fields["status_raw"].strip("`")
    return fields


def collect() -> list[dict]:
    """rglob('[D]-...') treats brackets as char-class. Iterate manually instead."""
    items: list[dict] = []
    for p in BASE.rglob("*-DONE-*.md"):
        if "_archive" in p.parts or "_index" in p.parts or "scripts" in p.parts:
            continue
        name = p.name
        if not (name.startswith("[D]-DONE-") or name.startswith("[W]-DONE-") or name.startswith("[U]-DONE-")):
            continue
        d = parse_stub(p)
        if d:
            d["prefix"] = name[1]  # 'D' / 'W' / 'U'
            items.append(d)
    items.sort(key=lambda d: d["id"])
    return items


def render_index(items: list[dict], status_prefix: str, title: str, note: str) -> str:
    filtered = [it for it in items if it["prefix"] == status_prefix]
    by_module = defaultdict(list)
    for it in filtered:
        by_module[it.get("module_name", "(unknown)")].append(it)

    out = [f"# {title} — auto-generated\n"]
    out.append(f"_Generated by `scripts/regen-indexes.py` from stub filenames `[{status_prefix}]-DONE-*.md` under `bugs/`, `discoveries/`, `prd-asks/`._\n")
    out.append(f"_Triage date: {TRIAGE_DATE}._\n")
    out.append(note + "\n")
    out.append(f"**Total**: {len(filtered)} items\n")

    out.append("\n## By module / sheet\n")
    for mod in sorted(by_module.keys()):
        rows = by_module[mod]
        out.append(f"\n### `{mod}` — {len(rows)} items\n")
        out.append("| ID | Title | Tech layer | Raw status | Stub |")
        out.append("|---|---|---|---|---|")
        for it in rows:
            rel = it["path"].relative_to(BASE).as_posix()
            tech = it.get("tech_layer", "?")
            raw = it.get("status_raw", "?")
            # Markdown link: filename has [..] which conflict with link syntax — URL-encode
            url = "../" + rel.replace("[", "%5B").replace("]", "%5D")
            out.append(f"| {it['id']} | {it['title']} | `{tech}` | `{raw}` | [open]({url}) |")

    return "\n".join(out) + "\n"


def render_distribution(items: list[dict]) -> str:
    """High-level overview — replaces the `Distribution` section of old done-summary.md."""
    by_prefix = defaultdict(int)
    by_layer = defaultdict(int)
    by_folder = defaultdict(int)
    for it in items:
        by_prefix[it["prefix"]] += 1
        by_layer[it.get("tech_layer", "?")] += 1
        rel = it["path"].relative_to(BASE).as_posix()
        folder = "/".join(rel.split("/")[:2])
        by_folder[folder] += 1

    total = len(items)
    out = ["# Triage status distribution — auto-generated\n"]
    out.append(f"_Total tracked: {total} items (from {TRIAGE_DATE} triage of `Edit UX_UI_MDLZ.xlsx`)_\n")
    out.append("\n## By status prefix\n")
    out.append("| Prefix | Count | % | Meaning |")
    out.append("|---|---|---|---|")
    label = {"D": "Done — fixed by SLG, MDLZ verified", "W": "WIP — đang làm hoặc pending dev pickup", "U": "Unmapped — raw status không khớp convention, cần BA clarify"}
    for p in ("D", "W", "U"):
        c = by_prefix[p]
        pct = f"{c * 100 / total:.1f}%" if total else "0%"
        out.append(f"| `[{p}]` | {c} | {pct} | {label[p]} |")
    out.append(f"| **Total** | **{total}** | 100% | |\n")

    out.append("\n## By tech_layer (guess from heuristic)\n")
    out.append("| Tech layer | Count |")
    out.append("|---|---|")
    for k in sorted(by_layer.keys()):
        out.append(f"| `{k}` | {by_layer[k]} |")

    out.append("\n## By folder\n")
    out.append("| Folder | Count |")
    out.append("|---|---|")
    for k in sorted(by_folder.keys()):
        out.append(f"| `{k}/` | {by_folder[k]} |")

    out.append("\n## Notes\n")
    out.append("- `tech_layer` là **guess heuristic** từ keyword trong item text. Khi review từng stub, có thể override (đổi folder).")
    out.append("- Move stub giữa folder = thay đổi tech_layer. Re-run `regen-indexes.py` sau khi move.")
    out.append("- Khi 1 `[W]` chuyển thành `[D]`: rename file (`mv '[W]-...'.md '[D]-...'.md`) + thêm history row + re-run script.")

    return "\n".join(out) + "\n"


def main() -> int:
    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    items = collect()

    (INDEX_DIR / "done-index.md").write_text(
        render_index(items, "D", "Done items (`[D]`)",
                     "> **Done** = MDLZ marked `Đã fixed` / `Đã sửa=True` in Excel. KHÔNG có nghĩa là verified bởi SLG QA — cần re-verify khi động đến code liên quan."),
        encoding="utf-8",
    )
    (INDEX_DIR / "wip-index.md").write_text(
        render_index(items, "W", "Work In Progress items (`[W]`)",
                     "> **WIP** = đang `In-dev`, `Đang fixing`, `Pending`, `SLG đã nhận yêu cầu`. Cần kiểm tra với DEV team xem ai đang làm + ETA."),
        encoding="utf-8",
    )
    (INDEX_DIR / "unmapped-index.md").write_text(
        render_index(items, "U", "Unmapped items (`[U]`)",
                     "> **Unmapped** = raw status text trong Excel không khớp convention `[D]/[W]/[-]`. Hầu hết là **câu hỏi của khách** (`sao lại dùng bộ lọc riêng ??`). BA cần clarify."),
        encoding="utf-8",
    )
    (INDEX_DIR / "status-distribution.md").write_text(render_distribution(items), encoding="utf-8")

    print(f"Wrote {len(items)} items to 4 index files in {INDEX_DIR}/")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
