-- ClickHouse DDL Snapshot: Panasonic PSV pipeline (analytics_workspace)
-- Generated: 2026-05-19 12:37 UTC
-- Total: 4 objects (psv_target + mv_psv_trigger + mv_psv_main + mv_psv)
-- Source: ghrx9lirdl.ap-southeast-1.aws.clickhouse.cloud
-- ----------------------------------------------------------------

-- ════════════════════════════════════════════════════
-- Object: psv_target
-- ════════════════════════════════════════════════════

CREATE TABLE analytics_workspace.psv_target
(
    `ops_optimize_id` Int32,
    `version` UInt64,
    `sys_customer_id` Nullable(Int32),
    `optimizer_name` Nullable(String) COMMENT 'Tên kết quả OPS_Optimizer (Thông tin trường lấy từ cột khác của bảng OPS_Optimizer)',
    `created_date` Nullable(DateTime64(6)) COMMENT 'Thời gian tạo kết quả',
    `created_by` LowCardinality(Nullable(String)) COMMENT 'Người tạo kết quả',
    `parent_modified_date` Nullable(DateTime64(6)),
    `parent_modified_by` LowCardinality(Nullable(String)),
    `date_from` Nullable(DateTime64(6)),
    `date_to` Nullable(DateTime64(6)),
    `is_save` Nullable(Bool),
    `is_container` Nullable(Bool),
    `is_balance_customer` Nullable(Bool),
    `is_balance_km_score` Nullable(Bool),
    `type_id` Nullable(Int32),
    `note` Nullable(String),
    `note_1` Nullable(String),
    `note_2` Nullable(String),
    `tracking_id` Nullable(Int64) COMMENT 'Mã kết quả DataRun (Thông tin trường lấy từ cột DataRun của bảng OPS_Optimizer)',
    `report_id` Nullable(Int64),
    `is_trip_edit_manual` Nullable(Bool) COMMENT 'Chuyển có chỉnh sửa',
    `reason_change` Nullable(String) COMMENT 'Lý do điều chỉnh',
    `status_name_detail_original` LowCardinality(Nullable(String)) COMMENT 'Loại điều chỉnh (Cột dev thêm để check thông tin StatusNameDetail có tồn tại ở đoạn JSON hay không)',
    `status_name_detail` LowCardinality(Nullable(String)) COMMENT 'Loại điều chỉnh (Rule: Chuyến điều chỉnh route khi IsTripEditManual = true và StatusNameDetail không có giá trị. Ngược lại là Chuyến tạo mới)',
    `order_code` Nullable(String) COMMENT 'Mã đơn hàng',
    `total_order` Nullable(Int64) COMMENT 'Tổng số đơn',
    `total_delivery` Nullable(Int64) COMMENT 'Tổng điểm giao',
    `total_ton` Nullable(Float64) COMMENT 'Tổng số tấn',
    `total_cbm` Nullable(Float64) COMMENT 'Tổng số CBM',
    `total_cod_unit_price` Nullable(Float64) COMMENT 'Tổng giá trị hàng hóa',
    `group_of_vehicle_code` LowCardinality(Nullable(String)) COMMENT 'Mã loại xe',
    `group_of_vehicle_name` LowCardinality(Nullable(String)) COMMENT 'Tên loại xe',
    `group_of_vehicle_size` LowCardinality(Nullable(String)) COMMENT 'Khung xe',
    `vehicle_no` LowCardinality(Nullable(String)) COMMENT 'Số xe',
    `max_capacity` Nullable(Float64) COMMENT 'Thể tích xe',
    `max_weight` Nullable(Float64) COMMENT 'Trọng tải xe',
    `vendor_name` LowCardinality(Nullable(String)) COMMENT 'Nhà vận tải',
    `main_cost` Nullable(Float64) COMMENT 'Phí chính',
    `additional_cost` Nullable(Float64) COMMENT 'Phụ phí',
    `total_cost` Nullable(Float64) COMMENT 'Tổng chi phí dự kiến',
    `total_distance` Nullable(Float64),
    `master_etd` Nullable(DateTime64(6, 'Asia/Ho_Chi_Minh')) COMMENT 'ETD chuyến',
    `master_eta` Nullable(DateTime64(6, 'Asia/Ho_Chi_Minh')) COMMENT 'ETA chuyến',
    `date_come_stock` Nullable(DateTime64(6, 'Asia/Ho_Chi_Minh')) COMMENT 'Thời gian đến điểm nhận',
    `vehicle_end_time` Nullable(DateTime64(6, 'Asia/Ho_Chi_Minh')) COMMENT 'Thời gian xe về kho',
    `report_modified_date` Nullable(DateTime64(6, 'Asia/Ho_Chi_Minh')) COMMENT 'Thời gian điều chỉnh',
    `report_modified_by` LowCardinality(Nullable(String)) COMMENT 'Người điều chỉnh',
    `group_of_product_code` Nullable(String) COMMENT 'Mã nhóm hàng',
    `group_of_product_name` Nullable(String) COMMENT 'Tên nhóm hàng',
    `product_code` Nullable(String) COMMENT 'Mã hàng hóa',
    `product_name` Nullable(String) COMMENT 'Tên hàng hóa',
    `location_from_code` LowCardinality(Nullable(String)) COMMENT 'Mã điểm nhận',
    `location_from_name` LowCardinality(Nullable(String)),
    `location_to_code` Nullable(String) COMMENT 'Mã điểm giao',
    `location_to_name` Nullable(String),
    `group_ids` Nullable(String),
    `order_ids` Nullable(String),
    `constraint_name` Nullable(String) COMMENT 'Vi phạm ràng buộc',
    `constraint_note` Nullable(String) COMMENT 'Ghi chú ràng buộc',
    `data_report` Bool,
    `is_deleted` Nullable(UInt8)
)
ENGINE = SharedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', version)
ORDER BY (ops_optimize_id, tracking_id, report_id)
SETTINGS allow_nullable_key = 1, index_granularity = 8192, async_insert = 1


-- ════════════════════════════════════════════════════
-- Object: mv_psv_trigger
-- ════════════════════════════════════════════════════

CREATE MATERIALIZED VIEW analytics_workspace.mv_psv_trigger TO analytics_workspace.psv_target
(
    `ops_optimize_id` Int32,
    `version` UInt64,
    `sys_customer_id` Int32,
    `optimizer_name` String,
    `created_date` DateTime64(6),
    `created_by` LowCardinality(String),
    `parent_modified_date` DateTime64(6),
    `parent_modified_by` LowCardinality(String),
    `date_from` DateTime64(6),
    `date_to` DateTime64(6),
    `is_save` Bool,
    `is_container` Bool,
    `is_balance_customer` Bool,
    `is_balance_km_score` Bool,
    `type_id` Int32,
    `note` String,
    `note_1` String,
    `note_2` String,
    `tracking_id` Int64,
    `report_id` Int64,
    `is_trip_edit_manual` Bool,
    `reason_change` String,
    `status_name_detail_original` LowCardinality(String),
    `status_name_detail` LowCardinality(String),
    `order_code` String,
    `total_order` Int64,
    `total_delivery` Int64,
    `total_ton` Float64,
    `total_cbm` Float64,
    `total_cod_unit_price` Float64,
    `group_of_vehicle_code` LowCardinality(String),
    `group_of_vehicle_name` LowCardinality(String),
    `group_of_vehicle_size` LowCardinality(String),
    `vehicle_no` LowCardinality(String),
    `max_capacity` Float64,
    `max_weight` Float64,
    `vendor_name` LowCardinality(String),
    `main_cost` Float64,
    `additional_cost` Float64,
    `total_cost` Float64,
    `total_distance` Float64,
    `master_etd` DateTime,
    `master_eta` DateTime,
    `date_come_stock` DateTime,
    `vehicle_end_time` DateTime,
    `report_modified_date` DateTime,
    `report_modified_by` LowCardinality(String),
    `group_of_product_code` String,
    `group_of_product_name` String,
    `product_code` String,
    `product_name` String,
    `location_from_code` LowCardinality(String),
    `location_from_name` LowCardinality(String),
    `location_to_code` String,
    `location_to_name` String,
    `group_ids` String,
    `order_ids` String,
    `constraint_name` String,
    `constraint_note` String,
    `data_report` Bool,
    `is_deleted` UInt8
)
AS SELECT
    ID AS ops_optimize_id,
    _peerdb_version AS version,
    coalesce(SYSCustomerID, -1) AS sys_customer_id,
    coalesce(OptimizerName, '') AS optimizer_name,
    coalesce(CreatedDate, toDateTime64('1970-01-01 00:00:00', 6)) AS created_date,
    CAST(coalesce(CreatedBy, ''), 'LowCardinality(String)') AS created_by,
    coalesce(ModifiedDate, toDateTime64('1970-01-01 00:00:00', 6)) AS parent_modified_date,
    CAST(coalesce(ModifiedBy, ''), 'LowCardinality(String)') AS parent_modified_by,
    coalesce(DateFrom, toDateTime64('1970-01-01 00:00:00', 6)) AS date_from,
    coalesce(DateTo, toDateTime64('1970-01-01 00:00:00', 6)) AS date_to,
    coalesce(IsSave, false) AS is_save,
    coalesce(IsContainer, false) AS is_container,
    coalesce(IsBalanceCustomer, false) AS is_balance_customer,
    coalesce(IsBalanceKMScore, false) AS is_balance_km_score,
    coalesce(TypeID, -1) AS type_id,
    coalesce(Note, '') AS note,
    coalesce(Note1, '') AS note_1,
    coalesce(Note2, '') AS note_2,
    coalesce(JSONExtractInt(v, 'TrackingID'), -1) AS tracking_id,
    coalesce(JSONExtractInt(v, 'ID'), -1) AS report_id,
    toBool(coalesce(JSONExtractBool(v, 'IsTripEditManual'), false)) AS is_trip_edit_manual,
    coalesce(JSONExtractString(v, 'ReasonChange'), '') AS reason_change,
    CAST(multiIf(NOT JSONHas(v, 'StatusNameDetail'), 'Không có cột', isNull(JSONExtractString(v, 'StatusNameDetail')) OR (JSONExtractString(v, 'StatusNameDetail') = ''), ' ', JSONExtractString(v, 'StatusNameDetail')), 'LowCardinality(String)') AS status_name_detail_original,
    CAST(multiIf((is_trip_edit_manual = true) AND (isNull(JSONExtractString(v, 'StatusNameDetail')) OR (JSONExtractString(v, 'StatusNameDetail') = '')), 'Chuyến điều chỉnh route', 'Chuyến tạo mới'), 'LowCardinality(String)') AS status_name_detail,
    coalesce(JSONExtractString(v, 'OrderCode'), '') AS order_code,
    coalesce(JSONExtractInt(v, 'TotalOrder'), 0) AS total_order,
    coalesce(JSONExtractInt(v, 'TotalDelivery'), 0) AS total_delivery,
    coalesce(JSONExtractFloat(v, 'TotalTon'), 0) AS total_ton,
    coalesce(JSONExtractFloat(v, 'TotalCBM'), 0) AS total_cbm,
    coalesce(JSONExtractFloat(v, 'TotalCODUnitPrice'), 0) AS total_cod_unit_price,
    CAST(coalesce(JSONExtractString(v, 'GroupOfVehicleCode'), ''), 'LowCardinality(String)') AS group_of_vehicle_code,
    CAST(coalesce(JSONExtractString(v, 'GroupOfVehicleName'), ''), 'LowCardinality(String)') AS group_of_vehicle_name,
    CAST(coalesce(JSONExtractString(v, 'GroupOfVehicleSize'), ''), 'LowCardinality(String)') AS group_of_vehicle_size,
    CAST(coalesce(JSONExtractString(v, 'VehicleNo'), ''), 'LowCardinality(String)') AS vehicle_no,
    coalesce(JSONExtractFloat(v, 'MaxCapacity'), 0) AS max_capacity,
    coalesce(JSONExtractFloat(v, 'MaxWeight'), 0) AS max_weight,
    CAST(coalesce(JSONExtractString(v, 'VendorName'), ''), 'LowCardinality(String)') AS vendor_name,
    coalesce(JSONExtractFloat(v, 'MainCost'), 0) AS main_cost,
    coalesce(JSONExtractFloat(v, 'AdditionalCost'), 0) AS additional_cost,
    coalesce(JSONExtractFloat(v, 'TotalCost'), 0) AS total_cost,
    coalesce(JSONExtractFloat(v, 'TotalDistance'), 0) AS total_distance,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'MasterETD')), toDateTime('1970-01-01 00:00:00')) AS master_etd,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'MasterETA')), toDateTime('1970-01-01 00:00:00')) AS master_eta,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'DateComeStock')), toDateTime('1970-01-01 00:00:00')) AS date_come_stock,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'VehicleEndTime')), toDateTime('1970-01-01 00:00:00')) AS vehicle_end_time,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'ModifiedDate')), toDateTime('1970-01-01 00:00:00')) AS report_modified_date,
    CAST(coalesce(JSONExtractString(v, 'ModifiedBy'), ''), 'LowCardinality(String)') AS report_modified_by,
    coalesce(JSONExtractString(v, 'GroupOfProductCode'), '') AS group_of_product_code,
    coalesce(JSONExtractString(v, 'GroupOfProductName'), '') AS group_of_product_name,
    coalesce(JSONExtractString(v, 'ProductCode'), '') AS product_code,
    coalesce(JSONExtractString(v, 'ProductName'), '') AS product_name,
    CAST(coalesce(JSONExtractString(v, 'LocationFromCode'), ''), 'LowCardinality(String)') AS location_from_code,
    CAST(coalesce(JSONExtractString(v, 'LocationFromName'), ''), 'LowCardinality(String)') AS location_from_name,
    coalesce(JSONExtractString(v, 'LocationToCode'), '') AS location_to_code,
    coalesce(JSONExtractString(v, 'LocationToName'), '') AS location_to_name,
    coalesce(JSONExtractRaw(v, 'GroupIds'), '[]') AS group_ids,
    coalesce(JSONExtractRaw(v, 'OrderIds'), '[]') AS order_ids,
    coalesce(JSONExtractString(v, 'ConstraintName'), '') AS constraint_name,
    coalesce(JSONExtractString(v, 'ConstraintNote'), '') AS constraint_note,
    if(empty(JSONExtractString(DataRun, 'DataReport')) OR (JSONExtractString(DataRun, 'DataReport') = '[]'), false, true) AS data_report,
    coalesce(_peerdb_is_deleted, 0) AS is_deleted
FROM tms_panasonic_prod.dbo_OPS_Optimizer
LEFT ARRAY JOIN JSONExtractArrayRaw(coalesce(JSONExtractString(DataRun, 'DataReport'), '[]')) AS v


-- ════════════════════════════════════════════════════
-- Object: mv_psv_main
-- ════════════════════════════════════════════════════

CREATE MATERIALIZED VIEW analytics_workspace.mv_psv_main
REFRESH EVERY 1 HOUR
(
    `tracking_id` String,
    `optimizer_name` String,
    `created_by` LowCardinality(String),
    `created_date` DateTime64(6),
    `is_trip_edit_manual` Bool,
    `status_name_detail` String,
    `order_code` String,
    `total_order` Int64,
    `total_delivery` Int64,
    `total_ton` Float64,
    `total_cbm` Float64,
    `total_cod_unit_price` Float64,
    `group_of_vehicle_code` LowCardinality(String),
    `group_of_vehicle_name` LowCardinality(String),
    `group_of_vehicle_size` LowCardinality(String),
    `vehicle_no` LowCardinality(String),
    `max_capacity` Float64,
    `max_weight` Float64,
    `vendor_name` LowCardinality(String),
    `main_cost` Float64,
    `additional_cost` Float64,
    `total_cost` Float64,
    `report_modified_by` LowCardinality(String),
    `report_modified_date` Nullable(DateTime),
    `reason_change` String,
    `constraint_name` String,
    `constraint_note` String,
    `group_of_product_code` String,
    `group_of_product_name` String,
    `product_code` String,
    `product_name` String,
    `location_from_code` LowCardinality(String),
    `location_to_code` String,
    `master_etd` Nullable(DateTime),
    `master_eta` Nullable(DateTime),
    `date_come_stock` Nullable(DateTime),
    `vehicle_end_time` Nullable(DateTime),
    `is_deleted` Nullable(Int8),
    `data_report` Bool
)
ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY (tracking_id, order_code)
SETTINGS allow_nullable_key = 1, index_granularity = 8192
DEFINER = helix SQL SECURITY DEFINER
AS SELECT
    tracking_id,
    optimizer_name,
    created_by,
    created_date,
    is_trip_edit_manual,
    status_name_detail,
    order_code,
    total_order,
    total_delivery,
    total_ton,
    total_cbm,
    total_cod_unit_price,
    group_of_vehicle_code,
    group_of_vehicle_name,
    group_of_vehicle_size,
    vehicle_no,
    max_capacity,
    max_weight,
    vendor_name,
    main_cost,
    additional_cost,
    total_cost,
    report_modified_by,
    nullIf(report_modified_date + toIntervalHour(7), toDateTime('1970-01-01 07:00:00')) AS report_modified_date,
    reason_change,
    constraint_name,
    constraint_note,
    group_of_product_code,
    group_of_product_name,
    product_code,
    product_name,
    location_from_code,
    location_to_code,
    nullIf(master_etd + toIntervalHour(7), toDateTime('1970-01-01 07:00:00')) AS master_etd,
    nullIf(master_eta + toIntervalHour(7), toDateTime('1970-01-01 07:00:00')) AS master_eta,
    nullIf(date_come_stock + toIntervalHour(7), toDateTime('1970-01-01 07:00:00')) AS date_come_stock,
    nullIf(vehicle_end_time + toIntervalHour(7), toDateTime('1970-01-01 07:00:00')) AS vehicle_end_time,
    is_deleted,
    data_report
FROM analytics_workspace.psv_target
FINAL
WHERE (is_deleted = 0) AND (data_report = true)


-- ════════════════════════════════════════════════════
-- Object: mv_psv
-- ════════════════════════════════════════════════════

CREATE MATERIALIZED VIEW analytics_workspace.mv_psv
REFRESH EVERY 30 MINUTE
(
    `ops_optimize_id` Int32,
    `version` UInt64,
    `sys_customer_id` Int32,
    `optimizer_name` String,
    `created_date` DateTime64(6),
    `created_by` LowCardinality(String),
    `parent_modified_date` DateTime64(6),
    `parent_modified_by` LowCardinality(String),
    `date_from` DateTime64(6),
    `date_to` DateTime64(6),
    `is_save` Bool,
    `is_container` Bool,
    `is_balance_customer` Bool,
    `is_balance_km_score` Bool,
    `type_id` Int32,
    `note` String,
    `note_1` String,
    `note_2` String,
    `tracking_id` String,
    `report_id` Int64,
    `is_trip_edit_manual` Bool,
    `order_code` String,
    `total_order` Int64,
    `total_delivery` Int64,
    `total_ton` Float64,
    `total_cbm` Float64,
    `total_cod_unit_price` Float64,
    `group_of_vehicle_code` LowCardinality(String),
    `group_of_vehicle_name` LowCardinality(String),
    `group_of_vehicle_size` LowCardinality(String),
    `vehicle_no` LowCardinality(String),
    `max_capacity` Float64,
    `max_weight` Float64,
    `vendor_name` LowCardinality(String),
    `main_cost` Float64,
    `additional_cost` Float64,
    `total_cost` Float64,
    `total_distance` Float64,
    `master_etd` DateTime,
    `master_eta` DateTime,
    `date_come_stock` DateTime,
    `vehicle_end_time` DateTime,
    `report_modified_date` DateTime,
    `group_product_code` String,
    `group_product_name` String,
    `product_code` String,
    `product_name` String,
    `location_from_code` LowCardinality(String),
    `location_from_name` LowCardinality(String),
    `location_to_code` String,
    `location_to_name` String,
    `group_ids` String,
    `order_ids` String,
    `constraint_name` String,
    `constraint_note` String,
    `data_report` Bool,
    `is_deleted` UInt8
)
ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY (ops_optimize_id, tracking_id, report_id, version)
SETTINGS allow_nullable_key = 1, index_granularity = 8192
DEFINER = `sql-console:vy.tao@gosmartlog.com` SQL SECURITY DEFINER
AS SELECT
    ID AS ops_optimize_id,
    _peerdb_version AS version,
    coalesce(SYSCustomerID, -1) AS sys_customer_id,
    coalesce(OptimizerName, '') AS optimizer_name,
    coalesce(CreatedDate, toDateTime64('1970-01-01 00:00:00', 6)) AS created_date,
    CAST(coalesce(CreatedBy, ''), 'LowCardinality(String)') AS created_by,
    coalesce(ModifiedDate, toDateTime64('1970-01-01 00:00:00', 6)) AS parent_modified_date,
    CAST(coalesce(ModifiedBy, ''), 'LowCardinality(String)') AS parent_modified_by,
    coalesce(DateFrom, toDateTime64('1970-01-01 00:00:00', 6)) AS date_from,
    coalesce(DateTo, toDateTime64('1970-01-01 00:00:00', 6)) AS date_to,
    coalesce(IsSave, false) AS is_save,
    coalesce(IsContainer, false) AS is_container,
    coalesce(IsBalanceCustomer, false) AS is_balance_customer,
    coalesce(IsBalanceKMScore, false) AS is_balance_km_score,
    coalesce(TypeID, -1) AS type_id,
    coalesce(Note, '') AS note,
    coalesce(Note1, '') AS note_1,
    coalesce(Note2, '') AS note_2,
    coalesce(JSONExtractString(v, 'TrackingID'), '') AS tracking_id,
    coalesce(JSONExtractInt(v, 'ID'), -1) AS report_id,
    toBool(coalesce(JSONExtractBool(v, 'IsTripEditManual'), false)) AS is_trip_edit_manual,
    coalesce(JSONExtractString(v, 'OrderCode'), '') AS order_code,
    coalesce(JSONExtractInt(v, 'TotalOrder'), 0) AS total_order,
    coalesce(JSONExtractInt(v, 'TotalDelivery'), 0) AS total_delivery,
    coalesce(JSONExtractFloat(v, 'TotalTon'), 0) AS total_ton,
    coalesce(JSONExtractFloat(v, 'TotalCBM'), 0) AS total_cbm,
    coalesce(JSONExtractFloat(v, 'TotalCODUnitPrice'), 0) AS total_cod_unit_price,
    CAST(coalesce(JSONExtractString(v, 'GroupOfVehicleCode'), ''), 'LowCardinality(String)') AS group_of_vehicle_code,
    CAST(coalesce(JSONExtractString(v, 'GroupOfVehicleName'), ''), 'LowCardinality(String)') AS group_of_vehicle_name,
    CAST(coalesce(JSONExtractString(v, 'GroupOfVehicleSize'), ''), 'LowCardinality(String)') AS group_of_vehicle_size,
    CAST(coalesce(JSONExtractString(v, 'VehicleNo'), ''), 'LowCardinality(String)') AS vehicle_no,
    coalesce(JSONExtractFloat(v, 'MaxCapacity'), 0) AS max_capacity,
    coalesce(JSONExtractFloat(v, 'MaxWeight'), 0) AS max_weight,
    CAST(coalesce(JSONExtractString(v, 'VendorName'), ''), 'LowCardinality(String)') AS vendor_name,
    coalesce(JSONExtractFloat(v, 'MainCost'), 0) AS main_cost,
    coalesce(JSONExtractFloat(v, 'AdditionalCost'), 0) AS additional_cost,
    coalesce(JSONExtractFloat(v, 'TotalCost'), 0) AS total_cost,
    coalesce(JSONExtractFloat(v, 'TotalDistance'), 0) AS total_distance,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'MasterETD')), toDateTime('1970-01-01 00:00:00')) AS master_etd,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'MasterETA')), toDateTime('1970-01-01 00:00:00')) AS master_eta,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'DateComeStock')), toDateTime('1970-01-01 00:00:00')) AS date_come_stock,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'VehicleEndTime')), toDateTime('1970-01-01 00:00:00')) AS vehicle_end_time,
    coalesce(parseDateTimeBestEffortOrNull(JSONExtractString(v, 'ModifiedDate')), toDateTime('1970-01-01 00:00:00')) AS report_modified_date,
    coalesce(JSONExtractString(v, 'GroupOfProductCode'), '') AS group_product_code,
    coalesce(JSONExtractString(v, 'GroupOfProductName'), '') AS group_product_name,
    coalesce(JSONExtractString(v, 'ProductCode'), '') AS product_code,
    coalesce(JSONExtractString(v, 'ProductName'), '') AS product_name,
    CAST(coalesce(JSONExtractString(v, 'LocationFromCode'), ''), 'LowCardinality(String)') AS location_from_code,
    CAST(coalesce(JSONExtractString(v, 'LocationFromName'), ''), 'LowCardinality(String)') AS location_from_name,
    coalesce(JSONExtractString(v, 'LocationToCode'), '') AS location_to_code,
    coalesce(JSONExtractString(v, 'LocationToName'), '') AS location_to_name,
    coalesce(JSONExtractRaw(v, 'GroupIds'), '[]') AS group_ids,
    coalesce(JSONExtractRaw(v, 'OrderIds'), '[]') AS order_ids,
    coalesce(JSONExtractString(v, 'ConstraintName'), '') AS constraint_name,
    coalesce(JSONExtractString(v, 'ConstraintNote'), '') AS constraint_note,
    if(empty(JSONExtractString(DataRun, 'DataReport')) OR (JSONExtractString(DataRun, 'DataReport') = '[]'), false, true) AS data_report,
    coalesce(_peerdb_is_deleted, 0) AS is_deleted
FROM tms_panasonic_prod.dbo_OPS_Optimizer
LEFT ARRAY JOIN JSONExtractArrayRaw(coalesce(JSONExtractString(DataRun, 'DataReport'), '[]')) AS v


